# Restrict SSH access on compute nodes, only allowing users with active jobs on node

- name: Edit pam.d/sshd in chroot
  lineinfile:
    path: "{{ chroot }}/etc/pam.d/sshd"
    state: present
    regex: "account required pam_slurm.so"
    line: "account required pam_slurm.so"
    insertafter: EOF
