# Restrict SSH access on compute nodes, only allowing users with active jobs on node

- name: Edit pam.d/sshd in chroot
  lineinfile:
    path: "{{ chroot }}/etc/pam.d/sshd"
    state: present
    regexp: "account    required\tpam_slurm.so"
    line: "account    required\tpam_slurm.so"
    insertafter: EOF
