# This playbook deploys the whole OpenHPC software stack

- name: Deploy OpenHPC
  hosts: all
  remote_user: afpaget
  become: yes
  become_method: sudo

  roles:
   # - install_bos
   # - enable_ohpc_repo
   # - add_provision
    - resource_management
