# This playbook deploys the whole OpenHPC software stack

- name: Deploy OpenHPC
  hosts: all
  remote_user: afpaget
  become: yes
  become_method: sudo

  roles:
     - install_bos
     - enable_ohpc_repo
     - resource_management
     - basic_warewulf
     - initial_bos_image
     - customise_sys_config
     - register_nodes_core
     - boot_nodes