# Add resource management services on master node

- name: Install Slurm server meta-package
  yum:
    name: ohpc-slurm-server
    state: present

- name: Identify resource manager hostname
  replace:
    path: /etc/slurm/slurm.conf
    regexp: 'ControlMachine=(.*)'
    replace: "ControlMachine={{ sms_name }}"
    backup: yes
