# Add base distro-provided Infiniband drivers to compute image
# Add IB supp

- name: Install Infiniband support group in compute image
  yum:
    name: "@Infiniband Support"
    state: present
    installroot: "{{ chroot }}"

- name: Install infinipath-psm in compute image
  yum:
    name: infinipath-psm
    state: present
    installroot: "{{ chroot }}"

- name: Enable RDMA in chroot
  shell: "chroot {{ chroot }} systemctl enable rdma"
