# Add ConMan to the cluster

- name: Install ConMan in headnode
  yum:
    name: conman-ohpc
    state: present

- name: Configure ConMan for compute nodes
  lineinfile:
    path: /etc/conman.conf
    state: present
    regexp: "CONSOLE name=\"'{{ c_name }}{{ item }}'\" dev=\"ipmi:'{{ bmc_host }}{{ bmc_ip|int + item|int }}'\" ipmiopts=\"'U:{{ bmc_username }},P:{{ bmc_password }},W:solpayloadsize'\""
    line: "CONSOLE name=\"'{{ c_name }}{{ item }}'\" dev=\"ipmi:'{{ bmc_host }}{{ bmc_ip|int + item|int }}'\" ipmiopts=\"'U:{{ bmc_username }},P:{{ bmc_password }},W:solpayloadsize'\""
    insertafter: EOF
  with_sequence:
    start=0
    end="{{ num_computes|int - 1}}"

- name: Start and enable ConMan
  service:
    name: conman
    state: restarted
    enabled: yes
