# Register the nodes for provisioning

# Set the provisioning interface as default networking device
- name: Set the gateway device in a temp file
  lineinfile:
    path: "/tmp/network.$$"
    state: present
    create: yes
    regexp: "GATEWAYDEV={{ eth_provison }}"
    line: "GATEWAYDEV={{ eth_provison }}"

- name: Import the temp gateway file
  shell: "wwsh -y file import /tmp/network.$$ --name network"

- name: Set network
  shell: "wwsh -y file set network --path /etc/sysconfig/network --mode=0644 --uid=0"

- name: Add nodes to warewulf data store
  shell: "wwsh -y node new {{ c_name }}{{ item }} --ipaddr={{ c_ip }}{{ c_ip_last|int + item|int }} --hwaddr={{ c_mac[item|int] }} -D {{ eth_provision }}"
  with_sequence:
    start=0
    end="{{ num_computes|int - 1}}"

- name: Define image for nodes
  shell: "wwsh -y provison set \"{{ c_name }}*\" --vnfs=centos7.4 --bootstrap=`uname -r`--files=dynamic_hosts,passwd,group,shadow,slurm.conf,munge.key,network"

- name: Restart DHCPD
  service:
    name: dhcpd
    state: restarted

- name: Update pxe
  shell: "wwsh pxe update"
