# Configure Bass Operating System for OpenHPC

- name: Add sms hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: "{{ sms_ip }} {{ sms_name }}"
    line: "{{ sms_ip }} {{ sms_name }}"
    insertafter: EOF

- name: Disable and stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Stop and disable SELinux
  selinux:
    state: disabled
