# Increase locked memory limits on the headnode and in the compute image

- name: Update memlock settings on master
  blockinfile:
    path: /etc/security/limits.conf
    state: present
    block: |
       \\* soft memlock unlimited
       \\* hard memlock unlimited
    insertbefore: "# End of file"

- name: Update memlock settings in compute image
  blockinfile:
    path: "{{ chroot }}/etc/security/limits.conf"
    state: present
    block: |
       \\* soft memlock unlimited
       \\* hard memlock unlimited
    insertbefore: "# End of file"
